FROM ubuntu:22.04

# Using the official MySQL image from Docker Hub
FROM mysql:latest

# Set environment variables to configure MySQL
ENV MYSQL_ROOT_PASSWORD=bhavs123
ENV MYSQL_DATABASE=chatapp_db
ENV MYSQL_HOST=localhost

# Expose MySQL port 3306
EXPOSE 3306
